import type { EmptyStateState, StudioPreset } from "../types";

export const DEFAULT_EMPTYSTATE_STATE: EmptyStateState = {
  title: "No reports yet",
  description: "Create your first report or import sample data to populate this workspace.",
  label: "Empty reports workspace",
  helper: "Empty state is announced as a region with optional next steps.",
  id: "reports-empty-state",
  ariaLabel: "No reports available",
  tabIndex: 0,
  width: 560,
  height: 360,
  gap: 16,
  padding: 28,
  radius: 24,
  borderWidth: 1,
  borderStyle: "solid",
  fontBucket: "google",
  fontSearch: "",
  systemFontIdx: 9,
  googleFontFamily: "Inter",
  fontSizeUnit: "px",
  fontStyle: "normal",
  textTransform: "none",
  textDecoration: "none",
  letterSpacing: 0,
  letterSpacingUnit: "px",
  lineHeight: 1.5,
  radiusLinked: true,
  radiusTL: 22,
  radiusTR: 22,
  radiusBR: 22,
  radiusBL: 22,
  shadowEnabled: true,
  shadowX: 0,
  shadowY: 8,
  shadowBlur: 24,
  shadowSpread: 0,
  shadowOpacity: 0.25,
  shadowColor: "#000000",
  focusRingEnabled: true,
  focusRingWidth: 2,
  focusRingOffset: 2,
  focusRingColor: "#38bdf8",
  transitionDuration: 200,
  transitionEasing: "ease",
  background: "#0f172a",
  foreground: "#e5eefb",
  muted: "#94a3b8",
  accent: "#38bdf8",
  border: "#334155",
  titleSize: 24,
  bodySize: 14,
  fontWeight: 750,
  previewState: "empty",
  disabled: false,
  role: "region",
  illustration: "chart",
  stateMode: "no-data",
  statusVariant: "info",
  showPrimaryAction: true,
  showSecondaryAction: true,
  primaryActionLabel: "Create report",
  secondaryActionLabel: "Import sample data",
  suggestions: ["Connect a data source", "Use the starter template", "Invite a teammate"],
  resources: ["Read setup guide", "Watch 2 minute tour"],
  layoutMode: "centered",
};

const presets: Array<Omit<StudioPreset, "state"> & { state: Partial<EmptyStateState> }> = [
  {
    id: "saas-reports-centered",
    family: "saas",
    archetype: "Reports",
    variant: "centered",
    size: "spacious",
    tags: ["empty", "analytics", "actions", "resources"],
    state: {},
  },
  {
    id: "commerce-search-empty",
    family: "commerce",
    archetype: "Search",
    variant: "results",
    size: "compact",
    tags: ["no-results", "search", "suggestions"],
    state: {
      title: "No matching products",
      description: "Try a broader query, remove filters, or browse the latest arrivals.",
      label: "Empty product search",
      helper: "Search result empty states should keep recovery actions close to the message.",
      id: "product-search-empty",
      ariaLabel: "No product search results",
      width: 460,
      height: 300,
      padding: 22,
      radius: 20,
      background: "#fff7ed",
      foreground: "#431407",
      muted: "#9a3412",
      accent: "#f97316",
      border: "#fed7aa",
      role: "status",
      illustration: "search",
      stateMode: "no-results",
      statusVariant: "warning",
      primaryActionLabel: "Clear filters",
      secondaryActionLabel: "Browse arrivals",
      suggestions: ["Check spelling", "Remove sale-only filter", "Try a category name"],
      resources: ["View popular searches"],
      layoutMode: "stacked",
    },
  },
  {
    id: "admin-inbox-empty",
    family: "admin",
    archetype: "Inbox",
    variant: "calm",
    size: "spacious",
    tags: ["empty", "inbox", "secondary-action"],
    state: {
      title: "Inbox zero",
      description: "There are no new messages waiting for review.",
      label: "Empty support inbox",
      helper: "Success empty states can still expose maintenance resources.",
      id: "support-inbox-empty",
      ariaLabel: "Support inbox is empty",
      background: "#ecfdf5",
      foreground: "#052e16",
      muted: "#047857",
      accent: "#10b981",
      border: "#a7f3d0",
      role: "status",
      illustration: "inbox",
      stateMode: "success",
      statusVariant: "success",
      primaryActionLabel: "Review closed tickets",
      secondaryActionLabel: "Manage routing",
      suggestions: ["Audit automations", "Review SLA dashboard"],
      resources: ["Open team playbook"],
    },
  },
  {
    id: "offline-sync-empty",
    family: "mobile",
    archetype: "Offline",
    variant: "system",
    size: "compact",
    tags: ["offline", "alert", "retry"],
    state: {
      title: "Content unavailable offline",
      description: "Reconnect to refresh this list and continue syncing changes.",
      label: "Offline empty list",
      helper: "Alert role is reserved for interruption-worthy connectivity states.",
      id: "offline-empty-state",
      ariaLabel: "Content unavailable while offline",
      width: 440,
      height: 280,
      background: "#111827",
      foreground: "#f9fafb",
      muted: "#d1d5db",
      accent: "#fbbf24",
      border: "#374151",
      role: "alert",
      illustration: "spark",
      stateMode: "offline",
      statusVariant: "warning",
      primaryActionLabel: "Retry sync",
      secondaryActionLabel: "Open cached items",
      suggestions: ["Check network connection", "Retry after reconnecting"],
      resources: ["Offline mode help"],
      layoutMode: "inline",
    },
  },
  {
    id: "permission-empty",
    family: "security",
    archetype: "Access",
    variant: "locked",
    size: "compact",
    tags: ["permission", "lock", "request-access"],
    state: {
      title: "You need access",
      description: "Ask an administrator to grant permission before this content appears.",
      label: "Restricted empty state",
      helper: "Permission states should explain ownership and the next request path.",
      id: "permission-empty-state",
      ariaLabel: "Permission required to view content",
      background: "#f8fafc",
      foreground: "#0f172a",
      muted: "#475569",
      accent: "#2563eb",
      border: "#cbd5e1",
      illustration: "lock",
      stateMode: "permission",
      statusVariant: "neutral",
      primaryActionLabel: "Request access",
      secondaryActionLabel: "Contact owner",
      suggestions: ["Confirm workspace membership", "Request the viewer role"],
      resources: ["Permission policy"],
      layoutMode: "sidebar",
    },
  },
  {
    id: "editorial-resources-empty",
    family: "editorial",
    archetype: "Resources",
    variant: "guided",
    size: "spacious",
    tags: ["resources", "onboarding", "suggestions"],
    state: {
      title: "No saved resources",
      description: "Save articles, templates, and checklists here for quick access.",
      label: "Empty saved resources",
      helper: "Resource chips give users useful next destinations without clutter.",
      id: "saved-resources-empty",
      ariaLabel: "No saved resources",
      background: "#f5f3ff",
      foreground: "#2e1065",
      muted: "#6d28d9",
      accent: "#8b5cf6",
      border: "#ddd6fe",
      illustration: "spark",
      primaryActionLabel: "Browse library",
      secondaryActionLabel: "Create checklist",
      suggestions: ["Start with recommended reads", "Save onboarding templates"],
      resources: ["Editorial guide", "Template gallery", "Team checklist"],
      layoutMode: "grouped",
    },
  },
];

export const EMPTYSTATE_PRESETS: StudioPreset[] = presets.map((preset) => ({
  ...preset,
  state: { ...DEFAULT_EMPTYSTATE_STATE, ...preset.state },
}));
